global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: "Team D"

rule_files:
  - "alert.rules"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "webserver"
    scrape_interval: 5s
    dns_sd_configs:
      - names: ["webserver"]
        port: 8000
        type: A
        refresh_interval: 5s

  - job_name: "redis-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["redis-exporter:9121"]
