name: ci

on: [push, pull_request]

jobs:
  client_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the client
        uses: actions/checkout@v1

      - name: Install npm packages
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/client
          npm install

      - name: Build app
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/client
          npm run build

      - name: Test app
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/client
          npm run test

  webserver_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/webserver
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          cd $GITHUB_WORKSPACE/webserver
          pip install pytest
          pytest

  modelserver_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/modelserver
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          cd $GITHUB_WORKSPACE/modelserver
          pip install pytest
          pytest
